[virsh] use read-only option to list all domains
If authentication is required to use virsh, sos will timeout on
'virsh list --all'. Use '-r' option to avoid this.

2016-02-10 00:24:02,761 WARNING: [plugin:virsh] command 'virsh list
--all' timed out after 300s

$ virsh list --all
Please enter your authentication name:
Please enter your password:
error: failed to connect to the hypervisor
error: no valid connection
error: authentication failed: Failed to step SASL negotiation: -1
(SASL(-1): generic failure: All-whitespace username.)

$ virsh -r list --all

 Id    Name                           State
----------------------------------------------------

Fixes: #761.

Signed-off-by: Germano Veit Michel <germano@redhat.com>